name: App2 Workflow

on: 
    workflow_dispatch:
      inputs:
        app_name:
          description: 'Name of the application'
          required: true
          default: 'app'

jobs:
  generate-output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate output
        id: generate
        run: |
          echo "Generating output..."
          echo '{"applicationsTool": ["app21", "app22", "app23"]}' > output.json

      - name: Upload output artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output.json