name: Action A

on: [push]

jobs:
  select-jobs:
    runs-on: ubuntu-latest
    outputs:
      selected_jobs: ${{ steps.select-jobs.outputs.selected_jobs }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install yq and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.6.1/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Read jobs configuration
        id: read-jobs
        run: |
          jobs=$(yq e '.jobs | map(.name)' jobs.yml | jq -c)
          echo "jobs=$jobs" >> $GITHUB_ENV

      - name: Select jobs
        id: select-jobs
        run: |
          selected_jobs=$(echo $jobs | jq -r '.[]' | fzf -m | jq -c -R -s 'split("\n") | map(select(length > 0))')
          echo "::set-output name=selected_jobs::$selected_jobs"

  call-action-b:
    needs: select-jobs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: ${{ fromJson(needs.select-jobs.outputs.selected_jobs) }}
    steps:
      - name: Call Action B
        uses: ./.github/actions/action-b
        with:
          job: ${{ matrix.job }}