name: App1 Workflow

on:
  workflow_dispatch:

jobs:
  generate-output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate output
        id: generate
        run: |
          echo "Generating output..."
          echo '{"applicationsTool": ["app1", "app2", "app3"]}' > output.json

      - name: Upload output artifact
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: output.json