name: Read Config

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  read-config:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.read.outputs.apps }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read config file
        id: read
        run: |
          apps=$(jq -c '.applicationsTool' config.json)
          echo "::set-output name=apps::$apps"
