name: Trigger Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Name of the application to deploy'
        required: true

jobs:
  generate-options:
    runs-on: ubuntu-latest
    outputs:
      options: ${{ steps.generate.outputs.options }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate options
        id: generate
        run: |
          options=$(jq -r '.applicationsTool[]' config.json | jq -R -s -c 'split("\n")[:-1]')
          echo "::set-output name=options::$options"

  trigger:
    needs: generate-options
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger deploy pipeline
        run: |
          app_name="${{ github.event.inputs.app_name }}"
          if [[ ! " ${options[@]} " =~ " ${app_name} " ]]; then
            echo "Invalid application name: $app_name"
            exit 1
          fi
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/YOUR_USERNAME/repo-B/actions/workflows/deploy.yml/dispatches \
            -d "{\"ref\":\"main\", \"inputs\": {\"app_name\": \"$app_name\"}}"
