name: Dynamic Jobs

on: [push]

jobs:
  generate-jobs:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.generate.outputs.apps }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read config file
        id: generate
        run: |
          apps=$(jq -c '.applicationsTool' config.json)
          echo "::set-output name=apps::$apps"

  request-approval:
    needs: generate-jobs
    runs-on: ubuntu-latest
    steps:
      - name: Request approval
        run: echo "Requesting approval for jobs: ${{ needs.generate-jobs.outputs.apps }}"
        env:
          JOBS: ${{ needs.generate-jobs.outputs.apps }}