name: Dynamic Jobs

on:
  workflow_dispatch:
    inputs:
      apps:
        description: 'List of applications'
        required: true

jobs:
  generate-jobs:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.generate.outputs.apps }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read config file
        id: generate
        run: |
          apps=$(jq -c '.applicationsTool'  ${{ fromJson(github.event.inputs.apps) }})
          echo "::set-output name=apps::$apps"

  jobs:
    needs: generate-jobs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app_name: ${{ fromJson(needs.generate-jobs.outputs.apps) }}
    steps:
      - name: Trigger deploy pipeline for ${{ matrix.app_name }}
        run: |
          echo "Triggering deploy for ${{ matrix.app_name }}"
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.SECRET_TOKEN }}" \
            https://api.github.com/repos/giannicaruana/demoPipelineCalled/actions/workflows/deploy.yml/dispatches \
            -d "{\"ref\":\"main\", \"inputs\": {\"app_name\": \"${{ matrix.app_name }}\"}}"