name: Manual Job Selection with Dynamic Options

on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Select the job to run'
        required: true
        type: choice
        options: []

jobs:
  set-options:
    runs-on: ubuntu-latest
    outputs:
      options: ${{ steps.set-options.outputs.options }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read options from file
        id: set-options
        run: |
          options=$(cat options.txt | tr '\n' ',' | sed 's/,$//')
          echo "::set-output name=options::$options"

  job1:
    if: ${{ github.event.inputs.job == 'job1' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run job1
        run: echo "Running job1"

  job2:
    if: ${{ github.event.inputs.job == 'job2' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run job2
        run: echo "Running job2"

  job3:
    if: ${{ github.event.inputs.job == 'job3' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run job3
        run: echo "Running job3"
