name: Dynamic Jobs

on:
  workflow_dispatch:
    inputs:
      app_selection:
        description: 'Select the app to deploy (leave blank to deploy all)'
        required: false
        type: string
  push:

jobs:
  generate-jobs:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.generate.outputs.apps }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read config file
        id: generate
        run: |
          apps=$(jq -c '.applicationsTool' config.json)
          echo "::set-output name=apps::$apps"

  dynamic-jobs:
    needs: generate-jobs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app_name: ${{ fromJson(needs.generate-jobs.outputs.apps) }}
    steps:
      - name: Conditionally deploy based on app_selection
        run: |
          if [[ -z "${{ github.event.inputs.app_selection }}" || "${{ github.event.inputs.app_selection }}" == "${{ matrix.app_name }}" ]]; then
            echo "Triggering deploy for ${{ matrix.app_name }}"
            curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/giannicaruana/demoPipelineCalled/actions/workflows/deploy.yml/dispatches \
              -d "{\"ref\":\"main\", \"inputs\": {\"app_name\": \"${{ matrix.app_name }}\"}}"
          else
            echo "Skipping deploy for ${{ matrix.app_name }}"
          fi
