name: Dynamic Jobs

on: [push]

jobs:
  generate-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read config file
        id: read_config
        run: |
          echo "::set-output name=jobs::$(jq -c '.jobs' config.json)"

  # Dynamically create jobs based on the config file
  job_matrix:
    needs: generate-jobs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_name: ${{ fromJson(needs.generate-jobs.outputs.jobs) }}
    steps:
      - name: Run ${{ matrix.job_name }}
        run: echo "Running job: ${{ matrix.job_name }}"