name: Dynamic Jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      app_selection:
        description: 'Select the app to deploy (leave empty to skip deploy)'
        required: false
        type: string

jobs:
  generate-jobs:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.generate.outputs.apps }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read config file
        id: generate
        run: |
          apps=$(jq -c '.applicationsTool' config.json)
          echo "::set-output name=apps::$apps"

  dynamic-jobs:
    needs: generate-jobs
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.app_selection != '' }}
    strategy:
      matrix:
        app_name: [ "${{ github.event.inputs.app_selection }}" ]
    steps:
      - name: Trigger deploy pipeline for ${{ matrix.app_name }}
        run: |
          echo "Triggering deploy for ${{ matrix.app_name }}"
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.SECRET_TOKEN }}" \
            https://api.github.com/repos/giannicaruana/demoPipelineCalled/actions/workflows/deploy.yml/dispatches \
            -d "{\"ref\":\"main\", \"inputs\": {\"app_name\": \"${{ matrix.app_name }}\"}}"
