name: Dynamic Jobs

on:
  workflow_dispatch:
    inputs:
      apps:
        description: 'List of applications'
        required: true
      environment:
        description: 'Deployment environment'
        required: true

jobs:
  deploy-dev:
    if: contains(github.event.inputs.environment, 'dev')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app_name: ${{ fromJson(github.event.inputs.apps) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Trigger deploy pipeline for ${{ matrix.app_name }} in ${{ github.event.inputs.environment }}
        run: |
          echo "Triggering deploy for ${{ matrix.app_name }} in ${{ github.event.inputs.environment }}"
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.SECRET_TOKEN }}" \
            https://api.github.com/repos/giannicaruana/demoPipelineCalled/actions/workflows/deploy.yml/dispatches \
            -d "{\"ref\":\"main\", \"inputs\": {\"app_name\": \"${{ matrix.app_name }}\", \"environment\": \"dev\"}}"

    deploy-uat:
      if: contains(github.event.inputs.environment, 'uat')
      runs-on: ubuntu-latest
      depends-on: deploy-dev
      strategy:
        matrix:
          app_name: ${{ fromJson(github.event.inputs.apps) }}
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
  
        - name: Trigger deploy pipeline for ${{ matrix.app_name }} in ${{ github.event.inputs.environment }}
          run: |
            echo "Triggering deploy for ${{ matrix.app_name }} in ${{ github.event.inputs.environment }}"
            curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token ${{ secrets.SECRET_TOKEN }}" \
              https://api.github.com/repos/giannicaruana/demoPipelineCalled/actions/workflows/deploy.yml/dispatches \
              -d "{\"ref\":\"main\", \"inputs\": {\"app_name\": \"${{ matrix.app_name }}\", \"environment\": \"uat\"}}"

    deploy-prod:
      if: contains(github.event.inputs.environment, 'prod')
      runs-on: ubuntu-latest
      depends-on: deploy-uat
      strategy:
        matrix:
          app_name: ${{ fromJson(github.event.inputs.apps) }}
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
  
        - name: Trigger deploy pipeline for ${{ matrix.app_name }} in ${{ github.event.inputs.environment }}
          run: |
            echo "Triggering deploy for ${{ matrix.app_name }} in ${{ github.event.inputs.environment }}"
            curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token ${{ secrets.SECRET_TOKEN }}" \
              https://api.github.com/repos/giannicaruana/demoPipelineCalled/actions/workflows/deploy.yml/dispatches \
              -d "{\"ref\":\"main\", \"inputs\": {\"app_name\": \"${{ matrix.app_name }}\", \"environment\": \"prod\"}}"
            
  