name: Dynamic Jobs

on: [push]

jobs:
  generate-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read config file
        id: read_config
        run: |
          jobs=$(jq -c '.jobs' config.json)
          echo "jobs=$jobs" >> $GITHUB_ENV

  # Dynamically create jobs based on the config file
  dynamic-jobs:
    needs: generate-jobs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_name: ${{ fromJson(env.jobs) }}
    steps:
      - name: Run ${{ matrix.job_name }}
        run: echo "Running job : ${{ matrix.job_name }}"