name: Action A

on: [push]

jobs:
  select-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read jobs configuration
        id: read-jobs
        run: |
          jobs=$(cat jobs.yml | yq '.jobs | map(.name)')
          echo "jobs=$jobs" >> $GITHUB_ENV

      - name: Select jobs
        id: select-jobs
        run: |
          selected_jobs=$(echo $jobs | jq -r '.[]' | fzf -m)
          echo "selected_jobs=$selected_jobs" >> $GITHUB_ENV

  call-action-b:
    needs: select-jobs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: ${{ fromJson(needs.select-jobs.outputs.selected_jobs) }}
    steps:
      - name: Call Action B
        uses: ./.github/actions/action-b
        with:
          job: ${{ matrix.job }}