name: Dynamic Jobs

on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Select the job to run'
        required: true
        type: choice
        options:
          - job1
          - job2
          - job3
          - job4
          - job5

jobs:
  dynamic-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Trigger deploy pipeline for ${{ github.event.inputs.job }}
        run: |
          echo "Triggering deploy for ${{ github.event.inputs.job }}"
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.SECRET_TOKEN }}" \
            https://api.github.com/repos/giannicaruana/demoPipelineCalled/actions/workflows/deploy.yml/dispatches \
            -d "{\"ref\":\"main\", \"inputs\": {\"app_name\": \"${{ github.event.inputs.job }}\"}}"
