name: Trigger Pipeline

on: [push]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read config and trigger pipeline
        run: |
          applications=$(jq -r '.applicationsTool[]' config.json)
          for app in $applications; do
            curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token ${{ secrets.SECRET_TOKEN }}" \
              https://api.github.com/repos/giannicaruana/demoPipelineCalled/actions/workflows/deploy.yml/dispatches \
              -d "{\"ref\":\"main\", \"inputs\": {\"app_name\": \"$app\"}}"
          done